exp: mind-mlm-news
mode: train
tasks:
  - mlm
freeze_emb: false
load:
  load_ckpt: null
  relax_load: true
  load_model_only: true
policy:
  neg_ratio: 20
  epoch: 50
  epoch_start: 0
  lr: 0.0002
  batch_size: 100
  accumulate_batch: 1
  device: gpu
  n_warmup: 16000
  check_interval: -5
  store_interval: 5