dataset: Adressa-user
store:
  data_dir: /home/qijiong/Code/MINDRec/data/Adressa/4Week-v2/user/
  save_dir: saving/Adressa-user/L{num_hidden_layers}H{num_attention_heads}E{hidden_size}-B{batch_size}/
data:
  shuffle: true
  split:
    train: 8
    dev: 2
  order:
    - device
    - os
    - country
    - region
    - city
    - history
  append:
    - uid
bert_config:
  hidden_size: 768
  num_hidden_layers: 6
  num_attention_heads: 12
embedding:
  -
    vocab_name: nid
    vocab_type: numpy
    path: saving/Adressa/L3H12E768-B64/unfreeze-mlm/u-d768-e49.npy
    freeze: true
