dataset: Adressa
store:
  data_dir: /home/qijiong/Code/MINDRec/data/Adressa/news/
  save_dir: saving/Adressa/L{num_hidden_layers}H{num_attention_heads}E{hidden_size}-B{batch_size}/
data:
  shuffle: true
  split:
    train: 8
    dev: 2
  order:
    - title
    - desc
    - key
  append:
    - nid
bert_config:
  hidden_size: 768
  num_hidden_layers: 3
  num_attention_heads: 12
embedding:
  -
    vocab_name: language
    vocab_type: numpy
    path: /home/qijiong/Code/MINDRec/pretrained/norwegian_bert_uncased/word_embeddings.npy
    freeze: false
