dataset: MINDsmall
store:
  data_dir: data/MIND/MINDsmall-rec/news/
  save_dir: saving/MINDsmall/L{num_hidden_layers}H{num_attention_heads}E{hidden_size}-B{batch_size}/
data:
  shuffle: true
  split:
    train: 8
    dev: 2
  order:
    - title
    - subCat
    - abs
  append:
    - nid
    - cat
bert_config:
  hidden_size: 768
  num_hidden_layers: 3
  num_attention_heads: 12
embedding:
  -
    vocab_name: english
    vocab_type: bert_tf
    path: pretrained/bert-base-uncased
    freeze: false
